services:
  - type: web
    name: student-quiz-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "python app.py"
    plan: free
